// Auto-generated TypeScript types from C# DTOs
// Generated on: 2026-01-31T10:29:47.253Z
// Do not edit this file manually

export interface AuthResponse {
  success: boolean;
  message?: string | undefined;
  accessToken?: string | undefined;
  refreshToken?: string | undefined;
  expiresAt?: string | undefined;
  user?: UserInfo | undefined;
  errors: string[];
}

export interface UserInfo {
  id: string;
  userName: string;
  email: string;
  fullName?: string | undefined;
  phoneNumber?: string | undefined;
  isActive: boolean;
  createdAt: string;
  roles: string[];
}

export interface CategoryDto {
  id: string;
  name: string;
  slug?: string | undefined;
  isActive: boolean;
}

export interface CreateCategoryRequest {
  name: string;
  slug?: string | undefined;
  isActive: boolean;
}

export interface UpdateCategoryRequest {
  name: string;
  slug?: string | undefined;
  isActive: boolean;
}

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
  confirmNewPassword: string;
}

export interface ForgotPasswordRequest {
  email: string;
}

export interface ResetPasswordRequest {
  email: string;
  token: string;
  newPassword: string;
  confirmNewPassword: string;
}

export interface GameAccountDto {
  id: string;
  game: string;
  accountName: string;
  rank?: string | undefined;
  price: number;
  currency: string;
  isAvailable: boolean;
  createdAt: string;
  categoryId: string;
  categoryName: string;
}

export interface CreateGameAccountRequest {
  game: string;
  accountName: string;
  rank?: string | undefined;
  price: number;
  currency: string;
  isAvailable: boolean;
  categoryId: string;
}

export interface UpdateGameAccountRequest {
  game: string;
  accountName: string;
  rank?: string | undefined;
  price: number;
  currency: string;
  isAvailable: boolean;
  categoryId: string;
}

export interface LoginRequest {
  usernameOrEmail: string;
  password: string;
  rememberMe: boolean;
}

export interface PromotionDto {
  id: string;
  code: string;
  description?: string | undefined;
  discountPercent: number;
  startDate: string;
  endDate: string;
  createdAt: string;
  isActive: boolean;
}

export interface CreatePromotionRequest {
  code: string;
  description?: string | undefined;
  discountPercent: number;
  startDate: string;
  endDate: string;
  isActive: boolean;
}

export interface UpdatePromotionRequest {
  code: string;
  description?: string | undefined;
  discountPercent: number;
  startDate: string;
  endDate: string;
  isActive: boolean;
}

export interface PromotionQueryRequest {
  code?: string | undefined;
  isActive?: boolean | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  page: number;
  pageSize: number;
}

export interface RefreshTokenRequest {
  accessToken: string;
  refreshToken: string;
}

export interface RevokeTokenRequest {
  refreshToken: string;
}

export interface RegisterRequest {
  userName: string;
  email: string;
  password: string;
  confirmPassword: string;
  fullName?: string | undefined;
  phoneNumber?: string | undefined;
}

export interface RoleDto {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
}

export interface CreateRoleRequest {
  name: string;
  description?: string | undefined;
}

export interface UpdateRoleRequest {
  name: string;
  description?: string | undefined;
}

export interface UserDto {
  id: string;
  userName?: string | undefined;
  email?: string | undefined;
  fullName?: string | undefined;
  isActive: boolean;
  createdAt: string;
  roles: string[];
}

export interface CreateUserRequest {
  userName: string;
  email: string;
  password: string;
  fullName?: string | undefined;
  isActive: boolean;
  roles: string[];
}

export interface UpdateUserRequest {
  userName?: string | undefined;
  email?: string | undefined;
  fullName?: string | undefined;
  isActive: boolean;
}

export interface AssignRoleRequest {
  userId: string;
  roleName: string;
}

export interface RemoveRoleRequest {
  userId: string;
  roleName: string;
}

// Common API Response Types
export interface ApiResponse<T = any> {
  success: boolean;
  message?: string;
  data?: T;
  errors?: string[];
}

export interface PaginatedResponse<T = any> {
  data: T[];
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
  hasNext: boolean;
  hasPrevious: boolean;
}

export interface ApiError {
  message: string;
  errors?: string[];
  statusCode?: number;
}
